name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest #windows-2019

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: install conan
      run: pip install --upgrade conan
    - name: create build dir
      #run: mkdir build
      run: md build
    - name: conan install
      working-directory: build
      #run: conan install ..\cv-plot -s compiler.version='15'
      run: conan install ../cv-plot
    - name: cmake
      working-directory: build
      #run: cmake .. -G "Visual Studio 15 Win64"
      run: cmake .. -G "gcc"
    - name: build
      working-directory: cv-plot\build
      run: cmake --build . --config Release
