name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    #- name: install conan
    #  run: pip install --upgrade conan

    - name: create build dir
      run: mkdir build
    #- name: conan install
    #  working-directory: build
    #  run: conan install ..\cv-plot -s compiler.version='15'
    - name: dir1
      run: dir
    - name: dir2
      working-directory: build
      run: dir
    - name: cmake
      working-directory: build
      run: cmake ..\cv-plot -G "Visual Studio 15 Win64"
    - name: build
      working-directory: build
      run: cmake --build . --config Release
